# Generated by Django 4.2.27 on 2026-01-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="鑽\ue21a搧鍚嶇О", max_length=100, verbose_name="鍚嶇О"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="鍒涘缓鏃堕棿"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="鏇存柊鏃堕棿"),
                ),
            ],
            options={
                "verbose_name": "鑽\ue21a搧",
                "verbose_name_plural": "鑽\ue21a搧",
                "ordering": ["-created_at"],
            },
        ),
    ]
