# Generated by Django 4.2.27 on 2026-01-30 18:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("drugs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="drug",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "药品",
                "verbose_name_plural": "药品",
            },
        ),
        migrations.AddField(
            model_name="drug",
            name="expiry_date",
            field=models.DateField(
                blank=True, help_text="药品有效期", null=True, verbose_name="有效期"
            ),
        ),
        migrations.AddField(
            model_name="drug",
            name="stock",
            field=models.IntegerField(
                default=0,
                help_text="药品库存数量",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="库存",
            ),
        ),
        migrations.AlterField(
            model_name="drug",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="drug",
            name="name",
            field=models.CharField(help_text="药品名称", max_length=100, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="drug",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.CreateModel(
            name="MedicationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="领取的药品数量",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="领药数量",
                    ),
                ),
                (
                    "record_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_records",
                        to="drugs.drug",
                        verbose_name="药品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用药记录",
                "verbose_name_plural": "用药记录",
                "ordering": ["-record_time"],
            },
        ),
    ]
