# Generated by Django 4.2.27 on 2026-01-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drugs", "0002_alter_drug_options_drug_expiry_date_drug_stock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="drug",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="药品成本价格（元）",
                max_digits=10,
                verbose_name="成本价格",
            ),
        ),
    ]
