# Generated by Django 4.2.27 on 2026-01-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drugs", "0004_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicationrecord",
            name="prescription_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="处方编号，同一处方的记录具有相同的处方号",
                max_length=50,
                verbose_name="处方号",
            ),
        ),
    ]
