# Generated by Django 4.2.27 on 2026-01-31 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drugs", "0005_medicationrecord_prescription_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="drug",
            name="category",
            field=models.CharField(
                choices=[
                    ("antibiotic", "抗生素"),
                    ("antiviral", "抗病毒"),
                    ("antipyretic", "解热镇痛"),
                    ("cold", "感冒药"),
                    ("cardiovascular", "心血管"),
                    ("diabetes", "降糖药"),
                    ("digestive", "消化系统"),
                    ("respiratory", "呼吸系统"),
                    ("vitamin", "维生素"),
                    ("other", "其他"),
                ],
                default="other",
                help_text="药品分类",
                max_length=50,
                verbose_name="分类",
            ),
        ),
    ]
