# Generated by Django 4.2.27 on 2026-02-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drugs", "0006_drug_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicationrecord",
            name="record_time",
            field=models.DateTimeField(verbose_name="记录时间"),
        ),
    ]
