# Generated by Django 4.2.27 on 2026-04-02 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("drugs", "0007_remove_auto_now_add"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "公告",
                "verbose_name_plural": "公告",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "政策更新",
                "verbose_name_plural": "政策更新",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="medicationrecord",
            name="prescribed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="创建该条用药/处方记录的医师（用于撤销权限）",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prescriptions_written",
                to=settings.AUTH_USER_MODEL,
                verbose_name="开具医师",
            ),
        ),
        migrations.AddField(
            model_name="medicationrecord",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "有效"), ("CANCELLED", "已作废")],
                db_index=True,
                default="ACTIVE",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="头像"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="科室"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "管理员"),
                    ("doctor", "医生"),
                    ("pharmacist", "药剂师"),
                    ("patient", "患者"),
                ],
                default="patient",
                max_length=20,
                verbose_name="角色",
            ),
        ),
        migrations.CreateModel(
            name="InventoryAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_change",
                    models.IntegerField(help_text="正数为增加，负数为减少", verbose_name="数量变动"),
                ),
                ("reason", models.CharField(max_length=500, verbose_name="原因")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_adjustments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_adjustments",
                        to="drugs.drug",
                        verbose_name="药品",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存盘点/损溢",
                "verbose_name_plural": "库存盘点/损溢",
                "ordering": ["-created_at"],
            },
        ),
    ]
