# Generated by Django 4.2.27 on 2026-04-02 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("drugs", "0008_feature_extensions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("LOW_STOCK", "LOW_STOCK"),
                            ("EXPIRY", "EXPIRY"),
                            ("DISEASE_TREND", "DISEASE_TREND"),
                            ("ARRIVAL", "ARRIVAL"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("level", models.CharField(default="info", max_length=20)),
                ("content", models.TextField()),
                (
                    "target_role",
                    models.CharField(
                        choices=[
                            ("doctor", "doctor"),
                            ("pharmacist", "pharmacist"),
                            ("admin", "admin"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                (
                    "department",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "target_type",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("target_id", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "预警",
                "verbose_name_plural": "预警",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="drug",
            name="department",
            field=models.CharField(
                blank=True,
                default="",
                help_text="为空表示全院共用",
                max_length=100,
                verbose_name="所属科室",
            ),
        ),
        migrations.AddField(
            model_name="drug",
            name="expiry_warning_days",
            field=models.IntegerField(default=30, verbose_name="效期预警提前天数"),
        ),
        migrations.AddField(
            model_name="drug",
            name="min_stock",
            field=models.IntegerField(default=10, verbose_name="安全库存下限"),
        ),
        migrations.AddField(
            model_name="medicationrecord",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="作废时间"),
        ),
        migrations.AddField(
            model_name="medicationrecord",
            name="department",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100, verbose_name="科室"
            ),
        ),
        migrations.AddField(
            model_name="medicationrecord",
            name="disease_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=100,
                verbose_name="疾病/诊断标签",
            ),
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE_PRESCRIPTION", "CREATE_PRESCRIPTION"),
                            ("CANCEL_PRESCRIPTION", "CANCEL_PRESCRIPTION"),
                            ("STOCK_IN", "STOCK_IN"),
                            ("INVENTORY_ADJUST", "INVENTORY_ADJUST"),
                            ("UPDATE_DRUG", "UPDATE_DRUG"),
                            ("CREATE_USER", "CREATE_USER"),
                            ("UPDATE_USER_ROLE", "UPDATE_USER_ROLE"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("target_id", models.IntegerField(default=0)),
                ("detail", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "操作审计",
                "verbose_name_plural": "操作审计",
                "ordering": ["-created_at"],
            },
        ),
    ]
