# Generated by Django 4.2.27 on 2026-04-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drugs", "0009_enhancements_audit_alert_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="drug",
            name="specification",
            field=models.CharField(
                default="", help_text="药品规格，如片剂/胶囊", max_length=50, verbose_name="规格"
            ),
        ),
    ]
