# Generated by Django 4.2.27 on 2026-04-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drugs", "0011_remove_patient_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug",
            name="specification",
            field=models.CharField(
                blank=True,
                default="",
                help_text="药品规格，如片剂/胶囊/盒装",
                max_length=50,
                verbose_name="规格",
            ),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CREATE_PRESCRIPTION", "CREATE_PRESCRIPTION"),
                    ("CANCEL_PRESCRIPTION", "CANCEL_PRESCRIPTION"),
                    ("STOCK_IN", "STOCK_IN"),
                    ("INVENTORY_ADJUST", "INVENTORY_ADJUST"),
                    ("UPDATE_DRUG", "UPDATE_DRUG"),
                    ("CREATE_USER", "CREATE_USER"),
                    ("UPDATE_USER_ROLE", "UPDATE_USER_ROLE"),
                    ("CREATE_ANNOUNCEMENT", "CREATE_ANNOUNCEMENT"),
                    ("UPDATE_ANNOUNCEMENT", "UPDATE_ANNOUNCEMENT"),
                    ("DELETE_ANNOUNCEMENT", "DELETE_ANNOUNCEMENT"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
